name: Execution of ESLint on every Pull Request

on:
    pull_request:
        branches: [ $GITHUB_HEAD_REF ]

jobs:
    execute-linter:

        runs-on: ubuntu-latest

        steps:
            name: Install npm packages
            run: npm install

        steps:
            name: Run ESLint
            run: ./node_modules/.bin/eslint

        steps:
            name: Cleanup - Uninstall npm packages
            if: always()
            run: rmdir ./node_modules
        